version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-init-scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
